app:
  polling_interval_ms: 500

network:
  grpc:
    host: "0.0.0.0"
    port: 50051


strategies:
  - id: "mean_reversion_1"
    gateway: "paper trading" # Or alpaca
    database:
      journal: "trading_journal" # These values by default in the code, but user can specify a new name
      orders: "trading_orders" # Same thing here
  - id: "momentum_1"
    gateway: "paper trading"
    database:
      journal: "trading_journal" # These values by default in the code, but user can specify a new name
      orders: "trading_orders" # Same thing here
